### ISSUE TITLE
isntalled all files throws one error havent tested yet

### ISSUE THREAD

**Issue by yaboibutt3r** [BryceCanyonCounty/bcc-portals#21]
SCRIPT ERROR: @bcc-portals/server/versioncheck.lua:1: No such export initiate in resource bcc-utils

**Comment by JusCampin** [comment]
Make sure you have bcc-utils installed and running. It needs to be ensured before portals.

**Comment by yaboibutt3r** [comment]
I see where I messed up.. pays to read the directions carefully, didn't have them ensured before portals like a dummy. Thank you for the help!

**Comment by JusCampin** [comment]
Anytime! Glad you got it working.
